DROP TABLE "SCHEMA"."TABLE";
CREATE COLUMN TABLE "SCHEMA"."TABLE" (
"FIELD0" CHAR(3),
"FIELD1" CHAR(8),
"FIELD2" CHAR(16),
"FIELD3" CHAR(16),
"MEASURE1" INT,
"MEASURE2" INT)
PARTITION BY ROUNDROBIN PARTITIONS 5;
ALTER TABLE "SCHEMA"."TABLE" DISABLE AUTOMERGE;
IMPORT FROM '/sapmnt/log/test.ctl' WITH THREADS 16 BATCH 100000;
MERGE DELTA OF "SCHEMA"."TABLE";
ALTER TABLE "SCHEMA"."TABLE" ENABLE AUTOMERGE;
# 5 Partitions per node,  Threads CPU x Nodes, Batch 100000 - 200000